# Generated by Django 3.1.4 on 2021-04-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210407_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
