# Generated by Django 3.1.4 on 2021-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210409_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='occupation',
        ),
        migrations.AddField(
            model_name='interest',
            name='Genre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='Movie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
