# Generated by Django 3.1.4 on 2021-04-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210403_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='compp',
            name='Pimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
