# Generated by Django 3.1.4 on 2021-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210403_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compp',
            name='Pimage',
            field=models.ImageField(default='/media/Product_pics/default.jpg', upload_to='Product_pics'),
        ),
    ]
