# Generated by Django 3.1.4 on 2021-05-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210406_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='compp',
            name='Pprice',
            field=models.IntegerField(default=0),
        ),
    ]
